# Generated by Django 5.0.4 on 2024-05-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
