# Generated by Django 5.0.4 on 2024-05-07 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='user',
        ),
        migrations.AddField(
            model_name='usercompany',
            name='company',
            field=models.ManyToManyField(to='bi_report.company'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
